### ISSUE TITLE
colum and row index

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR_mimosa26_interpreter#2]
Hi,

is the column and row counted from 0 or 1?

**Comment by thirono** [comment]
MIMOSA's maunal starts row from 0. And EUDAQ-EUTelescope is also starts row/col from 0

**Comment by laborleben** [comment]
our analysis expects index starting from 1. This is just by convention, and not a technical issue.

**Comment by laborleben** [comment]
This is fixed in a new branch. See PR #4.
